### ISSUE TITLE
Alternate filtering options not working in documents view (6.0.0)

### ISSUE THREAD

**Issue by maniku1976** [eeditiones/tei-publisher-app#21] opened 2020-09-22 08:20 UTC
Hi,

Noticed the following while testing the filtering in the demo collection of TEI Publisher. There are three filtering options, title, author and file. Filtering by the default filter-by value, title, works as expected. E.g. filter by title, "boga*" (first title in the collection, Bogactwa mowy polskiej):

Parameters in url: `.../tei-publisher/index.html?tab=0&collection=test&filter=Boga*&filterBy=title`
Parameters array in console: `{start: 1, sort: "title", filter: "Boga*", browse: "title"}`

However, if one switches filter to author, it still filters by title and consequently finds nothing. E.g. filter by author, "Kant" (second title in the collection, Critik der reinen Vernunft, author Kant Immanuel):

Parameters in url are correct: `.../tei-publisher/index.html?tab=0&collection=test&filter=Kant&filterBy=author`
Parameters in the parameter array in console are not: `{start: 1, sort: "title", filter: "Kant", browse: "title"}`

This is further demonstrated by the fact that if one filters by author and a string found in a title, it returns results.

**Comment by tuurma** [comment] 2020-09-25 08:23
Thanks for the report, I confirm I can reproduce the issue

**Comment by tuurma** [comment] 2020-09-25 09:59
Underlying problem is value chosen for the select is not correctly set and serialized on submission

![image](https://user-images.githubusercontent.com/449468/94254030-74b3c500-ff26-11ea-8f94-7a90cf130e8b.png)

**Comment by tuurma** [comment] 2020-09-28 10:03
fixed with https://github.com/eeditiones/tei-publisher-components/pull/32/commits/e281fcf9a6f64f75832ed7f311d8666e3fcf7152

**Closed by tuurma** 2020-09-28 10:03 UTC
Labels: bug

**Comment by maniku1976** [comment] 2020-09-30 06:31
Hi,

Hope you don't mind me asking, but regarding this bug: do you know when the fix will be updated to the CDN? Thanks.

**Comment by tuurma** [comment] 2020-09-30 12:29
@maniku1976 hard to give exact date because unfortunately I pushed my fix to the branch for upcoming Publisher 7 and it's a bit of a puzzle to align all the elements (tei-publisher-app, components, new api etc) so that nothing breaks. Rather question of days I'd say.

**Comment by tuurma** [comment] 2020-10-01 09:16
Hi @maniku1976, Wolfgang just released patched pb-components https://github.com/eeditiones/tei-publisher-components/releases/tag/v1.3.2 and also TEI Publisher 6.0.2 which include this fix. In your app just change modules/config.xqm to point to 1.3.2 version of the webcomponents library.

**Comment by maniku1976** [comment] 2020-10-01 09:19
That's great to hear! Thank you very much for taking the time to post an update, greatly appreciated.
