### ISSUE TITLE
Issue trying to generate an app

### ISSUE THREAD

**Issue by medievallondoners** [eeditiones/tei-publisher-app#46] opened 2021-04-21 17:33 UTC
We keep getting the following error message after trying to generate an application: 

> _This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <exception>
> <path>/db/apps/siegedantioch-beta3/modules/lib/api.xql</path>
> <message>err:XQST0059 error found while loading module dapi: Error while loading module api/document.xql: error found while loading module pages: Error while loading module ../pages.xql: error found while loading module pm-config: Error while loading module ../pm-config.xql: error found while loading module pm-docx-tei: Permission denied to read module source from location hint URI '../transform/docx-tei-module.xql.</message>
> </exception>_
> 
> 

We tried the slack forum and they told us:

> "The permissions on modules/pm-config.xql in your generated app are wrong. Could you check what they are? The file should be owned by your app user and group "tei" and needs to be executable."

We checked and found that the file was indeed under a different group; however, we changed it, yet the error is still there.  Would someone be able to help us identify if this is an issue with TEI Publisher or just something we are missing on our end.

**Comment by tuurma** [comment] 2023-03-06 09:37
Can't reproduce, closing

**Closed by tuurma** 2023-03-06 09:37 UTC
