### ISSUE TITLE
Annotation pop-ups fail to load after toggling full page facsimile viewer

### ISSUE THREAD

**Issue by mschef** [eeditiones/tei-publisher-app#67] opened 2021-08-25 08:58 UTC
When viewing a document that consists of both transcription and facsimile image (i.e. in the [Dodis edition](https://teipublisher.com/exist/apps/dodis-facets/53168.xml)), annotations that are rendered as pop-ups in the transcription fail to load after toggling full page view on and off in the OpenSeadragon viewer. 
Tested with Firefox and Chrome on Windows.
(EDIT: same goes for data that is displayed in a collapsible drawer (cf. [Dantiscus Correspondence](https://teipublisher.com/exist/apps/dantiscus/transcriptions/IDL5855.xml))

**Comment by joewiz** [comment] 2021-08-25 13:11
I can confirm the bug with Chrome 92.0.4515.159 and Safari 14.1.2 on macOS 11.5.2.

**Comment by JoernT** [comment] 2023-03-08 13:28
The problem is OpenSeaDragon again - it will replace the whole body when entering full-screen throwing away everything that was there before. 

Lars and me looked at it and assume that OSD is just storing away the body DOM and fails to restore all the shadowROOTs in e.g. the pb-view elements. And that's what inspector shows:: the shadowDOMs are gone afterwards.

**Comment by JoernT** [comment] 2023-03-08 13:48
https://github.com/openseadragon/openseadragon/issues/1677

**Comment by JoernT** [comment] 2023-03-10 11:35
pushed fix [to 'pb-facsimile' branch](https://github.com/eeditiones/tei-publisher-components/tree/pb-facsimile)

**Closed by JoernT** 2023-03-10 11:35 UTC
Labels: bug
